import { ClerkProvider } from "@clerk/nextjs";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div
          data-theme="corporate"
          className=" h-screen w-full flex flex-row justify-center items-center"
        >
          <div> {children}</div>
        </div>
      </body>
    </html>
  );
}
